- name : loops remove 
  hosts: local
  connection: local
  become: yes
  tasks:  
  - name: remove packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - nginx
    - mysql
    - zip
